### ISSUE TITLE
GitHub organization name

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/discussions#1]
What should the organization name be?

- `d-martians`
- `d-community`
- `d-hub`
- `dlang-hub`
- `dlang-community`
- ...

**Comment by kozhevnikov-peter** [comment]
@I'd would like: **dlang-community**

**Comment by wilzbach** [comment]
> @I'd would like: dlang-community

I don't have a strong feeling about the name, but `dlang-community` is one of my favorites as well.
CC @ZombineDev

**Comment by wilzbach** [comment]
Okay as no one raised their voice against `dlang-community`, I changed the organization name ;-)

Thanks a lot for your input!
