### ISSUE TITLE
Notification: private repo for login credentials etc.

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/discussions#11]
@dlang-community/d-yaml  @dlang-community/harbored-mod @dlang-community/d-yaml 

We have created a private GH repo that can be used to exchange secrets (e.g. login credentials for DUB). It's currently at
https://github.com/wilzbach/dlang-community

Also everyone from this Org can join the private Gitter chat: https://gitter.im/dlang-community/private (there's an IRC bridge: https://irc.gitter.im/)

Lastly, of course there's a public gitter channel as well:

https://gitter.im/dlang-community/public

**Comment by leandro-lucarella-sociomantic** [comment]
Oh, I thought that repo was a mistake, I removed myself from it, feel free to add me again if you will :)
