### ISSUE TITLE
Should we adopt tinyendian?

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/discussions#12]
Tinyendian is a dependency of D-YAML and thus imho it makes sense to adopt it to the dlang-community as well, because otherwise we run into issues like:

> For maximum fun, this PR for tinyendian should also be merged: kiith-sa/tinyendian#3 (when that's done, I can adjust the repository path in the wrapfile).

https://github.com/kiith-sa/tinyendian/pull/3

CC @ximion @ZombineDev  @dlang-community/d-yaml

**Comment by ZombineDev** [comment]
https://github.com/kiith-sa/tinyendian/issues/4 ;)

**Comment by wilzbach** [comment]
(sent an "analog" mail)

**Comment by BBasile** [comment]
TinyEndian could also be a source file of in D-Yaml. [It was already proposed a while ago](https://github.com/dlang-community/D-YAML/issues/26).

**Comment by wilzbach** [comment]
> TinyEndian could also be a source file of D-Yaml. It was already proposed a while ago.

I guess this would make @ximion's life a lot easier.

While [downloads](http://code.dlang.org/api/packages/tinyendian/stats) on [DUB](http://code.dlang.org/packages/tinyendian) are high, only 3 stars & 3 forks (one of them being ximion's) and two years of inactivity means that it's probably not interesting as a separate library anyways.

=> I am fine with both approaches. Should we wait a couple of days to give @kiith-sa time to respond and otherwise just go with @BBasile's idea of copying tinyendian to D-YAML?

**Comment by BBasile** [comment]
I bet that the traffic (quite surprising !) is generated by D-YAML and or TravisCI. Can we know if it's used as dependency elsewhere ?

**Comment by wilzbach** [comment]
> I bet that the traffic (quite surprising !) is generated by D-YAML and or TravisCI

Yes, quite certainly

> Can we know if it's used as dependency elsewhere ?

Yes: https://libraries.io/dub/tinyendian

Dependencies on DUB:

![image](https://cloud.githubusercontent.com/assets/4370550/26262766/2c2a4734-3cd6-11e7-8762-17a9b0d342ea.png)

Dependencies on GH (=projects on DUB are filtered out)

![image](https://cloud.githubusercontent.com/assets/4370550/26262843/7d3092b4-3cd6-11e7-90d3-cb2618547a42.png)

So we are talking about:
- https://github.com/kiith-sa/tharsis.prof
- https://github.com/NickPapanastasiou/wrath (never published on DUB, made 3 years ago)

Maybe @NickPapanastasiou has an opinion?

**Comment by kiith-sa** [comment]
tinyendian transferred.

**Comment by ZombineDev** [comment]
Thanks @kiith-sa!
