### ISSUE TITLE
Link to Discord server

### ISSUE THREAD

**Issue by rikkimax** [dlang-community/discussions#16]
I'm creating a server under the dlang-community name.
It will need to be linked.

Invite link: https://discord.gg/mRubmKC

**Comment by wilzbach** [comment]
FYI: There's also #dlang-community on the DSlack for a while now. If anyone isn't on the DSlack yet. Shoot me a short mail - just "Slack" is enough.

**Comment by WebFreak001** [comment]
closing reason: another D community discord has been recently linked on the D website and is very active and can currently be considered the community discord
