### ISSUE TITLE
Q: Moving d-mans to dlang-community

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/discussions#19]
Background: Last year I got in touch with the Japanese D community and received this [lovely dump](https://wilzbach.github.io/d-mans) of D-mans. I even opened a [NG thread](http://forum.dlang.org/post/vccecaeunthhfgvkoija@forum.dlang.org) back then, but of course that's long forgotten.
Anyhow during this years' DConf Walter discovered them and was so positively affected that he wanted to dump all of them on dlang.org: https://github.com/dlang/dlang.org/pull/1648

My take home message here is that the d-man repo is simply too less known and instead of dumping them to dlang.org, I would propose to move them to `dlang-community`. It doesn't require any foreseeable maintenance.
What's your opinion on this?
This isn't our typical "orphan repo", but here the idea is (1) to improve its visibility and (2) give more people merge rights in case someone wants to work the d-mans.

Repo: https://github.com/wilzbach/d-mans

**Comment by BBasile** [comment]
There's absolutely no problem.

**Comment by ZombineDev** [comment]
+1

**Comment by wilzbach** [comment]
Thanks a lot for the positive feedback.
Moved: https://dlang-community.github.io/d-mans/meiz/

May the D-mans rest happily ever after :)
