### ISSUE TITLE
DMD as a library VS libdparse

### ISSUE THREAD

**Issue by BBasile** [dlang-community/discussions#22]
We should start taking care to the project that is DMD as a library, before a new generation of tools emerges. Instead we should think to use it to avoid a split and very annoying  problems for editor plugins writer. (e.g they certainly don't want to support 2 completion engines, 2 code formatters, 2 linters etc).

A very well known problem of libdparse is the compile-time features: `static if` evaluation, CTFE which will be handled by DMD as a library, I think.

**Comment by wilzbach** [comment]
Do you have any concrete ideas?
Imho DMD has a horrible API (because no one bothered about it) whereas libdparse is a real joy to work with.

Have you ever thought about transforming the AST from libdparse to DMD and thus getting semantic nearly for free?

**Comment by BBasile** [comment]
No idea. It's just a warning. I've realized what i'm gonna say after opening the topic but because of the memory management i think that DMDFE couldn't replace dparse in a near future.
