### ISSUE TITLE
Adoptation of std.experimental.xml

### ISSUE THREAD

**Issue by Kozzi11** [dlang-community/discussions#23]
Hi,
there is a dub package https://code.dlang.org/packages/std-experimental-xml, which I use in many of my project at work, however it seems author does not have time or intrest in it anymore.
It would be nice if this project could be move under dlang-community. So I can fixed if something does not work.

I can still maintain my own fork and dub package but this does not seems right way to do it.

**Comment by BBasile** [comment]
Recently during an IRC discussions i said that someone should finalize the project...although i never use XML this is a pity to leave it project on standby.

About the integration criterions: 
- on libraries.io we can see that there a just 1 dependent project which is few. 
- The other PR seems trivial but is opened since January.

I'm fifty fifty.

**Comment by wilzbach** [comment]
I recall that @burner wanted to revive this package.

@Kozzi11: I think it's a good idea (I really don't like the old std.xml) - do you think we could be successful in pinging @lodo1995 (maybe via private mail?). It would be nice if we can avoid the fork.

**Comment by Kozzi11** [comment]
@wilzbach I hope so. I find this [document](https://drive.google.com/file/d/0B2_hnTCdWtH-eEplQ3hZdnY2Wlk/view) on page 4 there are two mail contacts.

**Comment by burner** [comment]
I had contact with @lodo1995. He told me that he wants to restart working on it soon.

**Comment by burner** [comment]
@lodo1995 contacted me, saying he is abandoning the project. Moving it here, might be a good step in getting a better xml library into phobos (long term)

**Comment by wilzbach** [comment]
@lodo1995 @burner do you have the rights to move it here? Otherwise another easy way is to initiate a transfer request to my account.

**Comment by burner** [comment]
@wilzbach Could you please initiate the transfer request

**Comment by wilzbach** [comment]
> Could you please initiate the transfer request

AFAICT only the owner can initiate it?

**Comment by burner** [comment]
@wilzbach I will contact him

**Comment by wilzbach** [comment]
> @wilzbach I will contact him

Ping

**Comment by burner** [comment]
I wrote him a mail asking about this.

**Comment by wilzbach** [comment]
Ping @lodo1995 and @burner 
If he's dead - should we simply fork his repository into dlang-community?
We might be able to shoot a friendly mail to Sönke to change the DUB package url to dlang-community, otherwise we would need to find a new DUB name.

**Comment by burner** [comment]
@wilzbach I don't think so, I think he just lost interest. I would say fork, and ask Sönke to redirect.

**Comment by wilzbach** [comment]
Done: https://github.com/dlang-community/experimental.xml

It's shame though that we loose those 25 stars :/
Also it seems that he never registered his package on DUB (or it already got removed?), so I just registered:

https://code.dlang.org/packages/std-experimental-xml

for dlang-community. It might take a while for the DUB registry to catch on:

![image](https://user-images.githubusercontent.com/4370550/35482029-4cc4b5a8-042f-11e8-86ef-967e5a795994.png)

Also you should have merge rights ;-)

**Comment by wilzbach** [comment]
Closing as the repo has been moved now: https://github.com/dlang-community/experimental.xml
