### ISSUE TITLE
New members invited

### ISSUE THREAD

**Issue by BBasile** [dlang-community/discussions#24]
To my mind there are still slow downs in the way the PR are accepted. Several times since the org was created i had to self-merge, especially in dsymbol.

To solve this issue:
- a new team is created for libdparse, dsymbol and dcd
- are invited people who work on IDEs, editor plugins or contributors: @WebFreak001 (vs-code), @buggins (dlang-ide), @Antlord (understand parts of the libraries involved) and @EyalIO(weka).

Everything is always reversible so let's see.

With the hope to get more reviews and PRs.

**Comment by wilzbach** [comment]
Thanks a lot for this initiative. While I remained quite silent over the last weeks, I did read the work of the new contributors, so I can only say thank you and keep on doing the great stuff!
