### ISSUE TITLE
Create a bintray organization for dlang-community

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [dlang-community/discussions#25]
At Sociomantic we are using [Bintray](https://bintray.com/) to store packages build from our public repos. Packages are built using [fpm](https://github.com/jordansissel/fpm), so for now is Debian only and they are just a quick&dirty packaging for easy distribution, we don't intend to replace the proper packages each maintainer does for each particular distribution.

There are some tools (like hmod) that we need to package (we already do internally actually, but we want to do it publicly), so we wonder if there is interest in creating a dlang-community Bintray organization, or at least if there is no veto to move forward with this, because we are willing to do at least the initial setup and package hmod (and probably dfmt in a near future too).

We are using [makd](https://github.com/sociomantic-tsunami/makd) to build the package (but we use `fpm` in the background so we could just use that to avoid an extra dependency), [beaver](https://github.com/sociomantic-tsunami/beaver) to ease the uploading procedure and to build using docker in combination with [cachalot](https://github.com/sociomantic-tsunami/cachalot) which is used to generate base dlang images. In principle we'll use the same stack for dlang-community tools.

/cc @nemanja-boric-sociomantic

**Comment by leandro-lucarella-sociomantic** [comment]
BTW, this comes from https://github.com/sociomantic-tsunami/cachalot/pull/35.

**Comment by wilzbach** [comment]
Short answer: sounds great. I think (at least in the beginning) it will be mostly you using this, so the answer is actually more "no vote".

Let me know if you are stopped by permission issues etc.

**Comment by stefan-koch-sociomantic** [comment]
I am going to setup a bintray for dlang community.

**Comment by leandro-lucarella-sociomantic** [comment]
Progress: https://bintray.com/dlang-community/ and https://bintray.com/dlang-community/apt

@wilzbach or anybody else that want access, please create an account in bintray (you can login with GitHub credentials) and send me you username so I can add you.

**Comment by stefan-koch-sociomantic** [comment]
@dlang-community/dscanner alternatively you can set your bintray account name to me as well;

**Comment by ZombineDev** [comment]
I created a team for you nice people for Sociomantic: @dlang-community/sociomantic 
Let us know if you need any help with permissions and stuff.

**Comment by ZombineDev** [comment]
@stefan-koch-sociomantic Do you still need any help with permissions for BinTray?

**Comment by stefan-koch-sociomantic** [comment]
@ZombineDev not at the moment.

**Comment by leandro-lucarella-sociomantic** [comment]
I also created a fake (bot) user https://bintray.com/dlang-community-travis to use it's API key in the repos, so no personal API keys could be leaked.

**Comment by leandro-lucarella-sociomantic** [comment]
And added the credentials to the repos we want to create packages for at the moment (dfmt and harbored-mod) in the form of 2 env variables: `BINTRAY_USER` and `BINTRAY_KEY`.

**Comment by wilzbach** [comment]
Closing as AFAICT the bintray has been created.
