### ISSUE TITLE
stdx-allocator

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/discussions#27]
Due to many recent breakages with the ongoing development effort of std.experimental.allocator, we decided to make a snapshot of the 2.077.0 version and provide it via DUB, s.t. projects can depend on it _without_ risking breakage with the next D version. In other words, this is intended to be a LTS version of the allocator - available via DUB.

Is anyone opposed to the project being moved in this community space?

https://github.com/wilzbach/stdx-allocator

CC @edi33416

**Comment by JackStouffer** [comment]
Is the plan to backport bugfixes to this branch? Because I wouldn't call it an LTS version otherwise.

**Comment by wilzbach** [comment]
Closing as the repo has been moved over.
