### ISSUE TITLE
Integrating Dscanner and tools projects

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/discussions#3]
FYI: I just forked Dscanner and the related projects into the dlang-community organization and created a Dscanner team.

The reason for this is that it takes months for simple one-line fixes to reach "upstream" as Hackerpilot is often busy. More details and the discussion can be found here: https://github.com/Hackerpilot/Dscanner/issues/421

**Comment by BBasile** [comment]
Next logical step is to use the fork in Phobos.

**Comment by Hackerpilot** [comment]
It may be better to delete these forks so that I can do an ownership transfer to this organization. That way the issues won't be lost.

**Comment by rikkimax** [comment]
I'm only a member so I can't delete, @wilzbach you're an owner.

**Comment by wilzbach** [comment]
> It may be better to delete these forks so that I can do an ownership transfer to this organization. That way the issues won't be lost.

Unfortunately I missed this issue, but hopefully the new organization allows progress without depending on the availability of an individual.

> I'm only a member so I can't delete, @wilzbach you're an owner.

Made you an owner as well in case it's needed in the future (though I plan to better reachable in the future).
