### ISSUE TITLE
Appveyor Single VM

### ISSUE THREAD

**Issue by skl131313** [dlang-community/discussions#30]
Looks like there's only once VM running for Appveyor and it's shared across all projects on an account. Possibly creating a separate account for dmd on appveyor as that seems to use up a lot of time. Currently it looks like dlang and dlang-community repo's use the same "greenify" account. I think that might be yours @wilzbach

**Comment by wilzbach** [comment]
Yes and yes, please feel more than free to replace my account with yours. "greenify" is also used for dlang/dmd now, so it's rather clogged.

Just remember to go to ["Team"](https://ci.appveyor.com/team), create a new role that allows restarting builds and and add the "all team" from dlang-community to it. I just recently discovered that this is possible (new feature?), so this hasn't been done for dlang-community.

**Comment by wilzbach** [comment]
@skl131313 did you manage to do the migration of AppVeyor to another account?

Just a short heads-up in case you missed [Martin's announcement](http://forum.dlang.org/post/ronypzvsafxpqlpnxlsf@forum.dlang.org). DLang-Bot now won't auto-merge until all CIs pass. As discussed, feel free to remove failing windows jobs or nightlie when failures occur.

**Comment by skl131313** [comment]
Yah I moved everything under my account so it shouldn't be fighting with DMD anymore.

**Comment by wilzbach** [comment]
Thanks!
