### ISSUE TITLE
Basile wants owner status

### ISSUE THREAD

**Issue by rikkimax** [dlang-community/discussions#36]
So Basile wants owner role (he's pretty active), before I do change, does anybody want to object?

**Comment by wilzbach** [comment]
Promoted. @BBasile thanks a lot for your hard work!

**Comment by ghost** [comment]
Thanks but i see no change although for now i just need owner status to change a link in a project description.

**Comment by wilzbach** [comment]
Try again:

![image](https://user-images.githubusercontent.com/4370550/41300750-c4ccef06-6e66-11e8-9b8a-dc9220d650cd.png)

**Comment by ghost** [comment]
Yes i see it too now, thanks.
