### ISSUE TITLE
Adopt facebookarchive/dfuse

### ISSUE THREAD

**Issue by CyberShadow** [dlang-community/discussions#38]
https://github.com/facebookarchive/dfuse is archived and not accepting contributions, however there is still interest in using the project.

I have a fork at https://github.com/CyberShadow/dfuse with some fixes, and someone sent me a pull request, so we could use that as the base. If possible, it would also be nice to change http://code.dlang.org/packages/dfuse to point at the dlang-community fork (tags would still be there for old versions).

I use the library in a personal project I use regularly, so I'm interested in maintaining it.

Any thoughts?

**Comment by lesderid** [comment]
I use dfuse in a few personal projects as well, and made the PR @CyberShadow mentioned.

So far I've used my own copy (with edits) or @CyberShadow's fork through a git submodule, but it would be nice if this project could be adopted (and the dub package pointed to the new fork).

It's a little unfortunate that this project still has Facebook's fairly restrictive [patent grant](https://github.com/CyberShadow/dfuse/blob/88001b70cc6deebff2832067a79c32a61d58ef39/PATENTS).
Perhaps Facebook could agree to removing this patent grant, in case none of their patents are used in the package (@dsp?).

**Comment by CyberShadow** [comment]
> It's a little unfortunate that this project still has Facebook's fairly restrictive [patent grant](https://github.com/CyberShadow/dfuse/blob/88001b70cc6deebff2832067a79c32a61d58ef39/PATENTS).

IANAL but how is the patent grant a problem? As far as I understand, it doesn't restrict anything any more compared to if it wasn't there at all - it just *grants* rights as long as the described conditions are satisfied?

**Comment by lesderid** [comment]
(IANAL either, but Facebook's (pre-2015) patent grant could possibly be interpreted in a way that would allow Facebook to arbitrarily revoke the license. There has been a lot of discussion about this e.g. in relation to the React project, which Facebook in the end re-licensed to MIT, without the explicit patent grant. For more information, see e.g. https://en.wikipedia.org/wiki/React_(JavaScript_library)#Licensing_controversy.)

For what it's worth, I don't think this is much of an actual issue for this library in particular (and getting it adopted by dlang-community). It just makes the licensing situation slightly more complex, which is unfortunate especially because this project most likely does not actually use any patents owned by Facebook.

**Comment by wilzbach** [comment]
We can definitely adopt the package. I don't know how feasible it is to change the dub registry link, but I think a mail to Sönke could do the trick.

So in short: if no one objects to this in the next day(s), please feel free to transfer the project.

**Comment by CyberShadow** [comment]
OK, I transferred it:

https://github.com/dlang-community/dfuse

- Do I need to grant any explicit access OSLT?
- How do we go about updating the Dub registry?
- Anything to do with the repository itself? Add a tag, maybe?

**Comment by CyberShadow** [comment]
Ping on this especially the Dub registry question. Who maintains code.dlang.org these days?

**Comment by wilzbach** [comment]
It's still only Sönke.

**Comment by CyberShadow** [comment]
@s-ludwig Whenever you find a minute :)

**Comment by s-ludwig** [comment]
I'd transfer ownership of the registry package to one of you two, the github target can then be changed using the registry UI. Who would prefer to be the maintainer? Vladimir?

**Comment by CyberShadow** [comment]
I am OK with being the maintainer. Whoever is in charge of dlang-community (Sebastian?) would also be appropriate.

**Comment by s-ludwig** [comment]
Should be listed in your package list now. Also, @extrawurst, FYI.

**Comment by CyberShadow** [comment]
Seems to work, thank you! I guess I'll make a tag to include the latest compilation fixes.
