### ISSUE TITLE
Adding DUB Build to CI, and minimum supported version of frontend/DMD? (dfmt, dscanner, dcd, etc..)

### ISSUE THREAD

**Issue by skl131313** [dlang-community/discussions#4]
Would basically be to ensure running DUB builds the projects successfully. Having a minimum supported version of DMD would also be nice to have, to have tests for each version in the CI to ensure they build. It'll make it easier to ensure no breaking changes occur with older versions. I don't know if DUB has a flag to specify which version to use but it does seem to have an env variable `$D_FRONTEND_VER` that could be used to warn if it is not in the supported range.

**Comment by wilzbach** [comment]
I think all these projects already have Travis configured and set up. You just need to add more versions to it, see e.g. 
- https://github.com/libmir/mir/blob/master/.travis.yml
- https://github.com/libmir/mir-algorithm/blob/master/.travis.yml

>  don't know if DUB has a flag to specify which version to use but it does seem to have an env variable $D_FRONTEND_VER that could be used to warn if it is not in the supported range.

No there's any explicit support in DUB yet.

**Comment by wilzbach** [comment]
@skl131313 I interpret this issue mostly as setting up Travis for all repos. This was handled in https://github.com/dlang-community/discussions/issues/7#issuecomment-302882117 and should hopefully work smoothly on all repos. Also as mentioned AFAICT there's no support in dub for D_FRONTEND and imho the only thing that we can do, is test every repo with a comprehensive list of compilers.
-> I am closing this. Feel free to reopen if you disagree,
