### ISSUE TITLE
Adoption of setup-dlang (GitHub action)

### ISSUE THREAD

**Issue by WebFreak001** [dlang-community/discussions#41]
there is a repository at https://github.com/mihails-strasuns/setup-dlang which can be used to easily download and install dmd or ldc in the GitHub CI (GitHub Actions)

It tests itself, has a few stars and is used in a few projects. (At least in mine)

Other actions for this were setup-dmd (by me) which has now been superseded by setup-dlang. Currently I am not aware of any further action scripts available, other than the docker container, which is restricted to only running on linux.

With adoption it could be then referenced using `dlang-community/setup-dlang` in the actions workflows which would look more professional and is easier to remember.

This project has been created less than 2 weeks ago by mihails-strasuns and seems to be stable. Maintenance would mostly be just fixing installation bugs for upcoming or legacy versions. Other than mihails-strasuns also kinke (Martin Kinkelin) and me have contributed to it. The project is written in typescript.

Also need to ask @mihails-strasuns for moving it here and adding them as member. (would create issue there if members here would think it would fit into dlang-community)

**Comment by mihails-strasuns** [comment]
I am happy to move it :)

**Comment by rikkimax** [comment]
Github actions is currently in beta. It is not fully rolled out.
Lets wait for it to mature up first and see how things go.

**Comment by WebFreak001** [comment]
how about now?

**Comment by wilzbach** [comment]
Sorry for the late reply.
@mihails-strasuns I sent out an invite to the dlang-community organization. If more permissions are required to move the project, please let me know. We can either make you admin or you temporarily transfer the project to an admin.

**Comment by mihails-strasuns** [comment]
Sure. Moved.

**Comment by mihails-strasuns** [comment]
https://github.com/dlang-community/setup-dlang

**Comment by wilzbach** [comment]
Cool! 
I created a CI team and added @WebFreak001 to it and invited @geod24:

![image](https://user-images.githubusercontent.com/4370550/83648337-36307e00-a5b6-11ea-98fb-d9e1b6ebbcef.png)

I doubt it will ever be necessary, but please feel more than free to give me or some of the other dlang-community admins a ping whenever required. I will try to respond sooner next time ;-)

**Comment by WebFreak001** [comment]
uh did someone test if the old namespace still works?

**Comment by mihails-strasuns** [comment]
It should for a while - github keeps redirects upon transfers. Don't know for how long exactly though.

**Comment by mihails-strasuns** [comment]
I also need to add a small readme for maintainers about branching model and regenerating node_modules / js files. There are few peculiar things to remember about.

**Comment by WebFreak001** [comment]
the default actions template has a validator to check if you pushed correctly, did you keep that in or remove it?

**Comment by Geod24** [comment]
> It should for a while - github keeps redirects upon transfers. Don't know for how long exactly though.

[I think they are quite conservative](https://www.github.com/D-Programming-Language/phobos).
By the way there was this issue which is related: https://github.com/dlang-community/setup-dlang/issues/13

**Comment by mihails-strasuns** [comment]
> the default actions template has a validator to check if you pushed correctly, did you keep that in or remove it?

I don't remember anything about it. Right now it simply tests itself on push / PR.

**Comment by WebFreak001** [comment]
well this one was the one I had from the typescript-actions template but it seems they removed it again from the template, not sure why

https://github.com/WebFreak001/setup-dmd/blob/c3e7bbdb2b250f7a0278ffe1637340846d273385/.github/workflows/checkin.yml

**Comment by Geod24** [comment]
Can this be closed ?
