### ISSUE TITLE
Adoption of d2sqlite3

### ISSUE THREAD

**Issue by biozic** [dlang-community/discussions#46]
I'm the author of [d2sqlite3](https://github.com/biozic/d2sqlite3), one of several wrappers around SQLite, which is apparently useful to some users, but which I have trouble finding time to maintain and fix issues.

@Geod24 pointed me to dlang-community, and I'm willing to transfer ownership to whoever is ok to continue maintaining it.

**Comment by Geod24** [comment]
Thanks! Indeed the project has a few thousands downloads, 61 stars, 14 contributors, and 24 forks so it would be nice to have it here. You can transfer it in the [settings](https://github.com/biozic/d2sqlite3/settings). It's probably simpler to transfer it to me, and I'll move it to `dlang-community` and will give you maintainer access to it.

Paging possible interested party based on repository stats: @tchaloupka @mark-summerfield @denizzka let me know if anyone is interested in helping to maintain the project.

**Comment by Geod24** [comment]
Transfered, thanks! I created a team and set your role to maintainer.
