### ISSUE TITLE
Move toml/toml-temp to dlang-community organization

### ISSUE THREAD

**Issue by WebFreak001** [dlang-community/discussions#52]
I would like to propose we could move the toml or toml-temp package into dlang-community.

The package can be used to read and write the [TOML](https://toml.io/en/) file format.

In the recent tooling survey it is currently at about half the popularity of the dyaml package. (current results at 146 responses: DYAML: 15 use it sometimes, 6 use it often - toml/toml-temp: 7 use it sometimes, 2 use it often)

The toml-temp package by @o3o package is more updated / has code fixes, which I think would be best suited to be moved here.

The toml package by @Kripth is the original package, the author still seems to be active on GitHub, but didn't do a lot on that package recently.

@Kripth are you ok if we migrate the package on the dub registry to o3o or to a dlang-community hosted repository?

@o3o would you be willing to move the package in dlang-community (can keep you as admin for that repository as well) so other maintainers can be added more easily or in case you don't have time to maintain it anymore?

@ other dlang-community members, any objections to add this package here?

I would be willing to co-maintain it as well / at least review+merge PRs & tag releases.

**Comment by o3o** [comment]
Yes, I'm willing..

**Comment by Kripth** [comment]
Unfortunately I don't use D anymore but I'd sure appreciate if the community can maintain the package. I can transfer ownership of the original package if it makes the migration more convenient.

**Comment by WebFreak001** [comment]
thanks @Kripth, I might come back to you to change the repository URL in the dub registry, but we might be able to move it ourself as well.

@o3o awesome! if nobody else in the dlang-community group has anything to add I would invite you to the organization so you can move the toml-temp project to here, we can then rename it back to `toml` and change the ownership on the dub registry. If you don't mind, I would also be willing to maintain it along with you, so you could then also add me as maintainer in the repository settings.

**Comment by o3o** [comment]
@WebFreak001 Thank you very much Jan, I am quite flattered  to contribute as much as I can.

**Comment by WebFreak001** [comment]
@rikkimax could you invite o3o to the dlang-community group then, so we can move the toml library to it?

**Comment by rikkimax** [comment]
Okay invite sent.

**Comment by o3o** [comment]
toml-temp moved to [toml](https://github.com/dlang-community/toml)

**Comment by WebFreak001** [comment]
repository on DUB was moved to dlang-community now
