### ISSUE TITLE
Move ddox to dlang-community

### ISSUE THREAD

**Issue by WebFreak001** [dlang-community/discussions#53]
@s-ludwig currently https://github.com/rejectedsoftware/ddox/ is used e.g. in dub, which is a core D tool. However when needing to adjust something in ddox there are currently not a lot of code owners.

Do you think it makes sense to move ddox to dlang-community, so that we can have more admins for the project?

cc @Geod24

**Comment by Geod24** [comment]
Thanks for opening the issue. Emailed him as well. He's an owner of the org, so there shouldn't be any problem to move it.

**Comment by Geod24** [comment]
Ping @s-ludwig

**Comment by s-ludwig** [comment]
I've invited you two to the repository and tagged a release to mitigate the immediate issue. Before moving to dlang-community, I'd just like to have something in place that helps to avoid breaking vibed.org as far as possible. It will be hard to enforce compatibility w.r.t. styles and derived diet templates once there are more people with merge access.

**Comment by Geod24** [comment]
I don't see any invitation / have merge access AFAICS.
I don't think DDOX is going to see a flurry of activity once in dlang-community, but it will give us the ability to fix things when needed (e.g. the upcoming DIP1000 deprecations).

**Comment by s-ludwig** [comment]
This is what I got:
![grafik](https://user-images.githubusercontent.com/1645969/188823657-ae4f2411-805d-4205-9bb0-f2ffa710bbb2.png)

**Comment by Geod24** [comment]
Got it. The Github UI shows invitations for repositories, but you have to go to your emails for group invitations...

**Comment by WebFreak001** [comment]
moved to https://github.com/dlang/ddox now
