### ISSUE TITLE
Adoption guidelines

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/discussions#6]
I doubt that we will need sth. like this in the near future (of course having such an increased interest would be cool).

Anyways, I just wanted to put my ideas on this topic up here - it will probably be similar to the [Arch guidelines](https://wiki.archlinux.org/index.php/AUR_Trusted_User_Guidelines):

- popularity (this is hard to judge, but I guess GH stars are the best measurement that we have)
  Q: Is there enough interest from the general public, s.t. it's worth maintaining?
- competition
  Q: Is there a similar library with active development out there?
- sponsor
  Q: Is there someone that is willing have an idea at the development process?

**Comment by BBasile** [comment]
- maintainer
  Q: Is at least one of the member competent for the domain covered by the project ? If no is there anyone that will join ?
