### ISSUE TITLE
Guidelines for each repository (aka common standard)

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/discussions#7]
I am trying to collect a list of common standard / steps that we should do/enable for each repository:

1) CI integration
2) Set master branch to force-push protected (https://github.com/dlang-community/X/settings/branches)

![image](https://cloud.githubusercontent.com/assets/4370550/26131340/ac734ff6-3a99-11e7-8879-91f0b7ce31a7.png)

3) Q: Should we set "Require status checks to pass before merging"?

![image](https://cloud.githubusercontent.com/assets/4370550/26131352/bb70ad00-3a99-11e7-9f48-79a0699fb0a4.png)

For example, with Travis:

![image](https://cloud.githubusercontent.com/assets/4370550/26131363/d98caf3c-3a99-11e7-9b4b-29b70292a68c.png)

**Comment by BBasile** [comment]
3: Yes. the CI build duration are usually < 2 minutes. Low enough even if something has to be merged in emergency.

**Comment by wilzbach** [comment]
Okay I have enabled this for all of our maintained repos (except for [dsymbol](https://github.com/dlang-community/dsymbol/settings/branches/master) and [DGrammar](https://github.com/dlang-community/DGrammar/settings/branches/master) as they don't have a Travis config as of now) and I will soon open a PR that adds this to this README.

>  Low enough even if something has to be merged in emergency.

FYI: As you are an admin, GH still allows emergency pulls (tough even this could be disabled):

![image](https://cloud.githubusercontent.com/assets/4370550/26149331/31cd2798-3afa-11e7-865f-ab411bf748e3.png)

Another point that just came to my mind is common docs (see e.g. https://github.com/dlang-community/D-YAML/issues/57).
I guess it wouldn't be too difficult to maintain the same documentation setup for all repos and have one common host (S3, netlify, ...)

**Comment by wilzbach** [comment]
Another point for the list - thanks to @ZombineDev: 
- enable `dmd-nightly` and daily cron jobs at Travis

It's a new feature from Travis:

https://docs.travis-ci.com/user/cron-jobs/
https://blog.travis-ci.com/2016-12-06-the-crons-are-here

I have just enabled this on the Travis side and will make PRs for the repos later.

**Comment by wilzbach** [comment]
> I have just enabled this on the Travis side and will make PRs for the repos later.

- https://github.com/dlang-community/D-Scanner/pull/436
- https://github.com/dlang-community/DCD/pull/378
- https://github.com/dlang-community/dfix/pull/43
- https://github.com/dlang-community/dfmt/pull/280
- https://github.com/dlang-community/libdparse/pull/140
- D-YAML [already uses `dmd-nightly`](https://github.com/dlang-community/D-YAML/blob/master/.travis.yml)
- Tinyendian will use `dmd-nightly` [soon](https://github.com/dlang-community/tinyendian/pull/3)
- https://github.com/dlang-community/harbored-mod/pull/80

**Comment by wilzbach** [comment]
Closed by #10
